Document: microsocks
Title: Debian microsocks Manual
Author: <insert document author here>
Abstract: This manual describes what microsocks is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/microsocks/microsocks.sgml.gz

Format: postscript
Files: /usr/share/doc/microsocks/microsocks.ps.gz

Format: text
Files: /usr/share/doc/microsocks/microsocks.text.gz

Format: HTML
Index: /usr/share/doc/microsocks/html/index.html
Files: /usr/share/doc/microsocks/html/*.html
